name: CI - Maven with Cucumber

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      # Step 3: Create/Update configuration file
      - name: Create/Update configuration file
        run: |
          if [ -f configuration.properties ]; then
            grep -q "token=" configuration.properties && sed -i "s/token=.*/token=${{ secrets.token }}/" configuration.properties || echo "token=${{ secrets.token }}" >> configuration.properties
          else
            touch configuration.properties
            echo "token=${{ secrets.token }}" >> configuration.properties
          fi

      # Step 4: Run Maven build and Cucumber tests
      - name: Build with Maven and run Cucumber tests
        run: |
          CUCUMBER_PUBLISH_TOKEN=${{ secrets.CUCUMBER_REPORT_TOKEN }} mvn clean verify

      # Step 5: Upload test results to GitHub for visibility
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-report.html
          retention-days: 30
